# Generated by Django 3.1 on 2020-09-16 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Proizvoditel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='Zayavka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rel_zayavka', to='test_app.contract')),
            ],
        ),
        migrations.CreateModel(
            name='Tovar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('proizvoditel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rel_tovar', to='test_app.proizvoditel')),
                ('zayavka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_tovar', to='test_app.zayavka')),
            ],
        ),
    ]
